excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://adammethew.github.io
name: LiveAdmins
description: My awesome new site
author: Adam Methew
avatar: http://www.gravatar.com/avatar/09a402ecdf807f4df7ae8f96087cc595?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 